#ifndef _COLOR_OUT_H_
#define _COLOR_OUT_H_
#if defined __WIN32 || defined __WIN64
    #define WINDOWS
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_LOG_LINESIZE	(1024*2)

#define LOG_TYPE_NONE	0
#define LOG_TYPE_NORMAL 1
#define LOG_TYPE_WARNING 2
#define LOG_TYPE_ERROR 3

#ifdef WINDOWS

#include <windows.h> 

#define DBG_C_NONE	(FOREGROUND_GRAY | FOREGROUND_INTENSITY)  
#define DBG_C_RED	(FOREGROUND_RED|FOREGROUND_INTENSITY)
#define DBG_C_LIGHT_RED	(FOREGROUND_RED|FOREGROUND_INTENSITY)
#define DBG_C_GREEN 		(FOREGROUND_GREEN | FOREGROUND_INTENSITY )
#define DBG_C_LIGHT_GREEN (FOREGROUND_GREEN | FOREGROUND_INTENSITY )
#define DBG_C_BLUE	(FOREGROUND_BLUE | FOREGROUND_INTENSITY )
#define DBG_C_LIGHT_BLUE		(FOREGROUND_BLUE | FOREGROUND_INTENSITY )
#define DBG_C_DARY_GRAY 	(FOREGROUND_GRAY | FOREGROUND_INTENSITY )
#define DBG_C_CYAN			(FOREGROUND_BLUE |FOREGROUND_GREEN|FOREGROUND_INTENSITY )
#define DBG_C_LIGHT_CYAN	(FOREGROUND_GREEN |FOREGROUND_BLUE|FOREGROUND_INTENSITY )
#define DBG_C_PURPLE			(FOREGROUND_RED |FOREGROUND_BLUE|FOREGROUND_INTENSITY )
#define DBG_C_LIGHT_PURPLE 	(FOREGROUND_RED |FOREGROUND_GREEN|FOREGROUND_INTENSITY )
#define DBG_C_BROWN 		(FOREGROUND_GREEN | FOREGROUND_INTENSITY )
#define DBG_C_YELLOW 	(FOREGROUND_RED| FOREGROUND_GREEN | FOREGROUND_INTENSITY )
#define DBG_C_LIGHT_GRAY 	(FOREGROUND_GRAY | FOREGROUND_INTENSITY )
#define DBG_C_WHITE 	(FOREGROUND_GRAY | FOREGROUND_INTENSITY) 
#else

#define DBG_C_NONE         "\033[m"
#define DBG_C_RED          "\033[0;32;31m"
#define DBG_C_LIGHT_RED    "\033[1;31m"
#define DBG_C_GREEN        "\033[0;32;32m"
#define DBG_C_LIGHT_GREEN  "\033[1;32m"
#define DBG_C_BLUE         "\033[0;32;34m"
#define DBG_C_LIGHT_BLUE   "\033[1;34m"
#define DBG_C_DARY_GRAY    "\033[1;30m"
#define DBG_C_CYAN         "\033[0;36m"
#define DBG_C_LIGHT_CYAN   "\033[1;36m"
#define DBG_C_PURPLE       "\033[0;35m"
#define DBG_C_LIGHT_PURPLE "\033[1;35m"
#define DBG_C_BROWN        "\033[0;33m"
#define DBG_C_YELLOW       "\033[1;33m"
#define DBG_C_LIGHT_GRAY   "\033[0;37m"
#define DBG_C_WHITE        "\033[1;37m"

#endif


void LOG(int iLogType, char* szFmt, ...);


#ifdef __cplusplus
}
#endif

#endif
